import type { Metadata } from "next";
import "./globals.css";
import { Quicksand } from "next/font/google";
import Link from "next/link";
const quickSand = Quicksand({
  subsets: ["latin"],
  weight: '500',
  display: 'swap',
  variable: "--font-quicksand"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

        className={`${quickSand.className} antialiased`}
      >
        <nav className="text-center">
          <Link href={'/'} className=" mt-5 text-4xl ">Mykyta Tarakanov</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
